# Site Settings
name: Krajša izobraževanja UM FERI
title: Krajša izobraževanja UM FERI
description: >
  Razvoj družbe narekuje nenehno posodabljanje kompetenc za obvladovanje obstoječih in prihodnjih izzivov. S krajšimi izobraževanji naslavljamo družbene, osebne in potrebe trga dela... <br><a href="/vec/" style="text-decoration: none; font-weight: bold; color: #DBA40B;">Več...</a>

show_hero: true
menu:
  - title: Domov
    url: /
  - title: Več
    url: /vec
  - title: Kontakt
    url: /kontakt

# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true

# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "si"
catalog_url: "catalog_url"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  courses:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - courses
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude:
  [
    "docs/",
    "vendor/",
    "LICENSE",
    "CHANGELOG.md",
    "jekflix.gemspec",
    "package.json",
    "package-lock.json",
    "node_modules",
    "initpost.sh",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "README.md",
  ]

# Theme
version: v3.1.2

# App connection link(url)
urlApi: localhost/pmd/api/:course
