name: Predlogi krajših izobraževanj
title: Predlogi krajših izobraževanj
description: Cilj spodnjega nabora vsebin je preveriti zainteresiranost za razvoj izbranih krajših izobraževanj Univerze v Mariboru.
show_hero: true
menu:
  - title: Doma
    url: /
  - title: O nas
    url: /o-nas
  - title: Kontakt
    url: /kontakt
